src/Entity/Messages.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessagesRepository")
 */
class Messages
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tickets", inversedBy="messages")
     */
    private $ticket_assign;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     */
    private $message_author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getTicketAssign(): ?Tickets
    {
        return $this->ticket_assign;
    }

    public function setTicketAssign(?Tickets $ticket_assign): self
    {
        $this->ticket_assign = $ticket_assign;

        return $this;
    }

    public function getMessageAuthor(): ?User
    {
        return $this->message_author;
    }

    public function setMessageAuthor(?User $message_author): self
    {
        $this->message_author = $message_author;

        return $this;
    }
}

src/Entity/Tickets.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TicketsRepository")
 */
class Tickets
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="tickets")
     */
    private $assign_to;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Messages", mappedBy="ticket_assign")
     */
    private $messages;

    public function __construct()
    {
        $this->assign_to = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getAssignTo(): Collection
    {
        return $this->assign_to;
    }

    public function addAssignTo(User $assignTo): self
    {
        if (!$this->assign_to->contains($assignTo)) {
            $this->assign_to[] = $assignTo;
        }

        return $this;
    }

    public function removeAssignTo(User $assignTo): self
    {
        if ($this->assign_to->contains($assignTo)) {
            $this->assign_to->removeElement($assignTo);
        }

        return $this;
    }

    /**
     * @return Collection|Messages[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setTicketAssign($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getTicketAssign() === $this) {
                $message->setTicketAssign(null);
            }
        }

        return $this;
    }
}

src/Form/TicketsType.php
<?php
namespace App\Form;
use App\Entity\Tickets;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
class TicketsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', TextType::class)
        ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Tickets::class,
        ));
    }
}

src/Controller/TicketsController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Entity\Tickets;
use App\Entity\User;
use App\Controller\MessagesController;
use App\Form\AssignToType;
use App\Form\TicketsType;
use App\Form\MessagesType;
use App\Repository\TicketsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tickets")
 */
class TicketsController extends AbstractController
{
    /**
     * @Route("/", name="tickets_index", methods={"GET"})
     */
    public function index(TicketsRepository $ticketsRepository): Response
    {
        $user = $this->getUser();
        if($user) {
            if(in_array("ROLE_ADMIN",$user->getRoles())) {
                return $this->render('tickets/index.html.twig',
                    ['tickets' => $ticketsRepository->findAll(),
                     'admin' => true]);
            }
            else{
                return $this->render('tickets/index.html.twig', ['tickets' => $user->getTickets(),
                                                                      'admin' => false]);
            }
        }
        else{
            return $this->redirectToRoute('home');
        }
    }

    /**
     * @Route("/new", name="tickets_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        if($user) {
            $ticket = new Tickets();
            $form = $this->createForm(TicketsType::class, $ticket);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $user->addTicket($ticket);
                $entityManager->persist($ticket);
                $entityManager->flush();

                return $this->redirectToRoute('tickets_index');
            }

            return $this->render('tickets/new.html.twig', [
                'ticket' => $ticket,
                'form' => $form->createView(),
            ]);
        }
        else{
            return $this->redirectToRoute('home');
        }
    }

    /**
     * @Route("/{id}", name="tickets_show", methods={"GET","POST"})
     */
    public function show(Tickets $ticket, Request $request): Response
    {
        $repository_messages= $this->getDoctrine()->getRepository(Messages::class);
        $getMessages = $repository_messages->findAll();

        $user = $this->getUser();
        $newMessage = new Messages();
        $form = $this->createForm(MessagesType::class, $newMessage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user->addMessage($newMessage);
            $ticket->addMessage($newMessage);
            $entityManager->persist($newMessage);
            $entityManager->flush();
            $id = $ticket->getId();
            return $this->redirectToRoute('tickets_show',['id' => $id]);
        }
        if(in_array("ROLE_ADMIN",$user->getRoles())) {
            $isadmin = true;
        }
        else{
            $isadmin = false;
        }
        return $this->render('tickets/show.html.twig',
            ['ticket' => $ticket,
             'form' => $form->createView(),
             'messages' => $getMessages,
                'admin' => $isadmin]);
    }

    /**
     * @Route("/{id}/edit", name="tickets_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tickets $ticket): Response
    {
        $user = $this->getUser();
        if(in_array("ROLE_ADMIN",$user->getRoles())) {
            $form = $this->createForm(TicketsType::class, $ticket);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('tickets_index', ['id' => $ticket->getId()]);
            }

            $formAssignTo = $this->createForm(AssignToType::class);
            $formAssignTo->handleRequest($request);

            if ($formAssignTo->isSubmitted() && $formAssignTo->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $user = $this->getDoctrine()->getRepository(User::class)->findBy(['id' => $request->get("assign_to")])[0];
                $user->addTicket($ticket);
                $entityManager->persist($ticket);
                $entityManager->flush();
                return $this->redirectToRoute('tickets_index', ['id' => $ticket->getId()]);
            }

            return $this->render('tickets/edit.html.twig', [
                'ticket' => $ticket,
                'form' => $form->createView(),
                'formAssignTo' => $formAssignTo->createView()
            ]);
        }
        else{
            return $this->redirectToRoute('tickets_index');
        }
    }

    /**
     * @Route("/{id}", name="tickets_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tickets $ticket): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            foreach ($ticket->getMessages() as $message) {
                $entityManager->remove($message);
            }
            $entityManager->remove($ticket);
            $entityManager->flush();
        }

        return $this->redirectToRoute('tickets_index');
    }
}

templates/tickets/_delete_form.html.twig
<form method="post" class="form-delete" action="{{ path('tickets_delete', {'id': ticket.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/tickets/_form.html.twig
{{ form_start(form) }}
    <label for="tickets_title">Title</label>
    <div class="form-group">
        {{ form_widget(form.title, { 'attr': {'class': 'form-control'} }) }}
    </div>
    <label for="tickets_content">Content</label>
    <div class="form-group">
        {{ form_widget(form.content, { 'attr': {'class': 'form-control'} }) }}
    </div>
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tickets/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tickets{% endblock %}

{% block body %}
    <h1>Edit Tickets</h1>
        {{ form_start(form) }}
        <label for="tickets_title">Title</label>
        <div class="form-group">
            {{ form_widget(form.title, { 'attr': {'class': 'form-control'} }) }}
        </div>
        <label for="tickets_content">Content</label>
        <div class="form-group">
            {{ form_widget(form.content, { 'attr': {'class': 'form-control'} }) }}
        </div>
    <div class="d-flex justify-content-start">
        <button class="btn btn-success edit-button">{{ button_label|default('Edit') }}</button>
        {{ form_end(form) }}
        {{ include('tickets/_delete_form.html.twig') }}
    </div>

    {{ form_start(formAssignTo) }}
    <h3>Assign ticket to user</h3>
    <div class="form-group">
        {{ form_widget(formAssignTo.users,{ 'attr': {'class': 'form-control'} })}}
    </div>
    <button class="btn btn-success" type="submit">Assign</button>
    {{ form_end(formAssignTo) }}

    <a href="{{ path('tickets_index') }}">back to list</a>
{% endblock %}

templates/tickets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tickets index{% endblock %}

{% block body %}
    <h1>Tickets index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Content</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.title }}</td>
                <td>{{ ticket.content }}</td>
                <td>
                    <a href="{{ path('tickets_show', {'id': ticket.id}) }}">show</a>
                    {% if admin %}
                        <a href="{{ path('tickets_edit', {'id': ticket.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/tickets/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tickets{% endblock %}

{% block body %}
    <h1>Create new Tickets</h1>

    {{ include('tickets/_form.html.twig') }}

    <a href="{{ path('tickets_index') }}">back to list</a>
{% endblock %}

templates/tickets/new_ticket.html.twig
{{ form_start(form) }}
    {{ form_row(form.title) }}
    {{ form_row(form.content) }}

<button type="submit">Create</button>
{{ form_end(form) }}

templates/tickets/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ ticket.title }}{% endblock %}

{% block body %}
    <article>
       <h1>{{ ticket.title }}</h1>
        <p>{{ ticket.content }}</p>
    </article>


    {% if admin %}
    <div class="d-flex justify-content-start btn-article">
        {{ include('tickets/_delete_form.html.twig') }}
    </div>
    {% endif %}

    <br><br>
    <div class="messages">
        <h2>Messages</h2>

    {% for message in messages %}
        {% if message.ticketAssign.id == ticket.id %}
            <hr>
            <h3>{{ message.content }}</h3>
            by {{ message.messageAuthor.username }}

            {% if admin %}
            <div class="d-flex justify-content-start">
                <a href="{{ path('messages_edit', {'id': message.id}) }}"><button class="btn btn-warning edit-button">Edit</button></a>
                {{ include('messages/_delete_form.html.twig') }}
            </div>
            {% endif %}

        {% endif %}
    {% endfor %}
    <hr>
    {{ include('messages/_form.html.twig') }}
    </div>
    <a href="{{ path('tickets_index') }}">back to list</a>
{% endblock %}

templates/tickets/ticket.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>{{ ticket.title }}</h1>
    {{ ticket.content }}

    <br><a href="edit/{{ ticket.id }}">edit</a>

    <h2>message</h2>

    {% for message in messages %}
        {% if message.ticketAssign.id == ticket.id %}
            <h3>{{ message.content }}</h3>
            by {{ message.messageAuthor.username }}
        {% endif %}
    {% endfor %}
    <br><br>
    {{ form_start(form) }}
    {{ form_row(form.content) }}

    <button type="submit">Create</button>
    {{ form_end(form) }}

    <br>
    {{ form_start(formAssign) }}
    <button type="submit">assign</button>
    {{ form_end(formAssign) }}

{% endblock %}